export const GLOSSARY = {
  'DCA':         'Defensive Counter Air — aircraft intercept threats to protected airspace',
  'RECCE':       'Reconnaissance — collects imagery/intelligence over a target area',
  'AI/ST':       'Air Interdiction/Strike — attacks ground targets behind enemy lines',
  'QRA':         'Quick Reaction Alert — on standby, ready to scramble in minutes',
  'AEW':         'Airborne Early Warning — radar surveillance platform',
  'DCA/CAP':     'DCA / Combat Air Patrol — the loitering intercept configuration',
  'BIT':         'Built-In Test — automatic self-test run before/after flight',
  'LRU':         'Line Replaceable Unit — a modular avionics box swapped at the flight line',
  'AU Steg 1':   'Avionikunderhåll step 1 — quick LRU swap, ~2h',
  'AU Steg 2/3': 'Avionikunderhåll step 2/3 — LRU swap with test, ~2h',
  'AU Steg 4':   'Avionikunderhåll step 4 — complex LRU replacement, ~6h',
  'Kompositrep': 'Composite repair — direct structural repair, ~16h',
  'FK steg 1-3': 'Flygkropp (airframe) maintenance step 1–3 — minor troubleshooting, ~4h',
  'Kris':        'Crisis phase — elevated readiness, restricted comms and movement',
  'Fred':        'Peacetime phase — normal operations, reduced alert level',
  'Krig':        'War phase — full combat ops, minimal margin for error',
  'GripenE':     'Gripen E — single-seat multirole fighter, latest production variant',
  'GripenF':     'Gripen F — two-seat variant for advanced training and operations',
  'GlobalEye':   'Saab GlobalEye — airborne early warning and control aircraft',
  'READY':       'Aircraft has passed pre-flight checks and is ready to be assigned',
  'MAINT':       'In maintenance — unavailable until fault is resolved',
  'AIRBORNE':    'Currently on an active mission',
  'RETURNING':   'In transit back to base — advance time for the aircraft to land',
  'GREY':        'Cannibalized — parts removed to support another aircraft',
  'ATO':         'Air Tasking Order — the daily schedule of planned missions',
  'ETA':         'Estimated Time of Arrival — hours until maintenance completes',
  'RECCE':       'Reconnaissance — intelligence-gathering mission over a target area',
}
